import { ConvexClient } from "convex/browser";
import fs from "fs";
import path from "path";
import { api } from "../convex/_generated/api";
import * as dotenv from "dotenv";
import { FunctionReturnType } from "convex/server";

// Load env from the devtools/clerk-sync/.env.local or similar if needed
// But usually for a dev script we might just rely on CONVEX_URL env var or 
// peeking into .env.local if running locally.
dotenv.config({ path: path.join(__dirname, "../.env.local") });

const CONVEX_URL = process.env.CONVEX_URL;

if (!CONVEX_URL) {
  console.error("Error: CONVEX_URL is not defined in .env.local");
  process.exit(1);
}

const client = new ConvexClient(CONVEX_URL);

// Output path: usually we want this in the main project's convex folder.
// Assuming this script is run from `devtools/clerk-sync/` or root
// We will target `../../convex/clerkTypes.ts` relative to `client/gen-types.ts` 
// (which is `devtools/clerk-sync/client/gen-types.ts`)
const OUT_PATH = path.resolve(__dirname, "../../../lib/clerk/orgs.ts");

console.log(`Connecting to Convex at ${CONVEX_URL}...`);

type RolesAndPermissions = FunctionReturnType<typeof api.sync.getAllRolesAndPermissions>;

/**
 * Generate TypeScript source content declaring Clerk role and permission types, constants, and role-to-permission mappings from the provided data.
 *
 * @param data - Object containing `roles` and `permissions` arrays as returned by the Clerk sync API; each role includes its key, name, and associated permission keys.
 * @returns The complete TypeScript file content (as a string) that defines `ClerkPermissionKey`, `ClerkRoleKey`, `PERMISSIONS`, `ROLES`, and `ROLE_PERMISSIONS`.
 */
function generateTypeFile(data: RolesAndPermissions) {
  const { roles, permissions } = data;

  // Generate union types
  const permissionKeys = permissions.map((p) => `"${p.key}"`).join(" | ") || "never";
  const roleKeys = roles.map((r) => `"${r.key}"`).join(" | ") || "never";

  const permissionConsts = permissions.map(p => `  "${p.key.toUpperCase()}": "${p.key}",`).join("\n");
  const roleConsts = roles.map(r => `  "${r.name}": "${r.key}",`).join("\n");

  // Also map roles to their permissions for easy lookup
  const rolePermissionsMap = roles.map(r => {
    // r.permissions is array of keys
    const perms = r.permissions.map((p) => `"${p.key}"`).join(", ");
    return `  "${r.key}": [${perms}],`;
  }).join("\n");

  return `/* eslint-disable */
/**
 * Generated by devtools/clerk-sync/client/gen-types.ts
 * DO NOT EDIT MANUALLY
 */

export type ClerkPermissionKey = ${permissionKeys};
export type ClerkRoleKey = ${roleKeys};

export const PERMISSIONS = {
${permissionConsts}
} as const;

export const ROLES = {
${roleConsts}
} as const;

export const ROLE_PERMISSIONS: Record<ClerkRoleKey, ClerkPermissionKey[]> = {
${rolePermissionsMap}
};
`;
}

// Initial reconcile with Clerk before watching
(async () => {
  console.log("🔄 Running initial reconcile with Clerk...");
  try {
    const result = await client.action(api.actions.reconcile, {});
    console.log(`✅ ${result}`);
  } catch (err) {
    console.error("❌ Reconcile failed:", err);
    process.exit(1);
  }

  console.log("👀 Watching for role/permission changes...");

  const unsubscribe = client.onUpdate(api.sync.getAllRolesAndPermissions, {}, (data) => {
    console.log(`Received update: ${data.roles.length} roles, ${data.permissions.length} permissions.`);

    const content = generateTypeFile(data);

    try {
      fs.writeFileSync(OUT_PATH, content, "utf-8");
      console.log(`✅ Updated ${OUT_PATH}`);
    } catch (err) {
      console.error(`❌ Error writing file:`, err);
    }
  });

  // Keep the process alive
  process.on("SIGINT", () => {
    console.log("Stopping...");
    unsubscribe();
    process.exit(0);
  });
})();
