/* eslint-disable */
/**
 * Generated by devtools/clerk-sync/client/gen-types.ts
 * DO NOT EDIT MANUALLY
 */

export type ClerkPermissionKey = "org:crm_accounts:delete" | "org:crm_accounts:global_delete" | "org:crm_accounts:update" | "org:crm_accounts:global_update" | "org:pipelines:global_create" | "org:pipelines:update" | "org:pipelines:global_delete" | "org:pipelines:read" | "org:pipelines:global_update" | "org:opportunities:delete" | "org:pipelines:global_read" | "org:opportunities:global_delete" | "org:opportunities:update" | "org:opportunities:global_create" | "org:opportunities:global_update" | "org:contacts:delete" | "org:opportunities:read" | "org:crm_accounts:global_create" | "org:contacts:update" | "org:opportunities:global_read" | "org:contacts:global_delete" | "org:crm_accounts:read" | "org:crm_accounts:global_read" | "org:pipelines:delete" | "org:contacts:global_update" | "org:contacts:global_create" | "org:contacts:global_read" | "org:campaigns:delete" | "org:campaigns:global_delete" | "org:campaigns:global_create" | "org:campaigns:read" | "org:sys_memberships:manage" | "org:sys_domains:read" | "org:campaigns:global_update" | "org:campaigns:update" | "org:sys_profile:delete" | "org:sys_memberships:read" | "org:sys_domains:manage" | "org:campaigns:global_read" | "org:sys_billing:manage" | "org:sys_profile:manage" | "org:contacts:read" | "org:sys_billing:read";
export type ClerkRoleKey = "org:admin" | "org:member";

export const PERMISSIONS = {
  "ORG:CRM_ACCOUNTS:DELETE": "org:crm_accounts:delete",
  "ORG:CRM_ACCOUNTS:GLOBAL_DELETE": "org:crm_accounts:global_delete",
  "ORG:CRM_ACCOUNTS:UPDATE": "org:crm_accounts:update",
  "ORG:CRM_ACCOUNTS:GLOBAL_UPDATE": "org:crm_accounts:global_update",
  "ORG:PIPELINES:GLOBAL_CREATE": "org:pipelines:global_create",
  "ORG:PIPELINES:UPDATE": "org:pipelines:update",
  "ORG:PIPELINES:GLOBAL_DELETE": "org:pipelines:global_delete",
  "ORG:PIPELINES:READ": "org:pipelines:read",
  "ORG:PIPELINES:GLOBAL_UPDATE": "org:pipelines:global_update",
  "ORG:OPPORTUNITIES:DELETE": "org:opportunities:delete",
  "ORG:PIPELINES:GLOBAL_READ": "org:pipelines:global_read",
  "ORG:OPPORTUNITIES:GLOBAL_DELETE": "org:opportunities:global_delete",
  "ORG:OPPORTUNITIES:UPDATE": "org:opportunities:update",
  "ORG:OPPORTUNITIES:GLOBAL_CREATE": "org:opportunities:global_create",
  "ORG:OPPORTUNITIES:GLOBAL_UPDATE": "org:opportunities:global_update",
  "ORG:CONTACTS:DELETE": "org:contacts:delete",
  "ORG:OPPORTUNITIES:READ": "org:opportunities:read",
  "ORG:CRM_ACCOUNTS:GLOBAL_CREATE": "org:crm_accounts:global_create",
  "ORG:CONTACTS:UPDATE": "org:contacts:update",
  "ORG:OPPORTUNITIES:GLOBAL_READ": "org:opportunities:global_read",
  "ORG:CONTACTS:GLOBAL_DELETE": "org:contacts:global_delete",
  "ORG:CRM_ACCOUNTS:READ": "org:crm_accounts:read",
  "ORG:CRM_ACCOUNTS:GLOBAL_READ": "org:crm_accounts:global_read",
  "ORG:PIPELINES:DELETE": "org:pipelines:delete",
  "ORG:CONTACTS:GLOBAL_UPDATE": "org:contacts:global_update",
  "ORG:CONTACTS:GLOBAL_CREATE": "org:contacts:global_create",
  "ORG:CONTACTS:GLOBAL_READ": "org:contacts:global_read",
  "ORG:CAMPAIGNS:DELETE": "org:campaigns:delete",
  "ORG:CAMPAIGNS:GLOBAL_DELETE": "org:campaigns:global_delete",
  "ORG:CAMPAIGNS:GLOBAL_CREATE": "org:campaigns:global_create",
  "ORG:CAMPAIGNS:READ": "org:campaigns:read",
  "ORG:SYS_MEMBERSHIPS:MANAGE": "org:sys_memberships:manage",
  "ORG:SYS_DOMAINS:READ": "org:sys_domains:read",
  "ORG:CAMPAIGNS:GLOBAL_UPDATE": "org:campaigns:global_update",
  "ORG:CAMPAIGNS:UPDATE": "org:campaigns:update",
  "ORG:SYS_PROFILE:DELETE": "org:sys_profile:delete",
  "ORG:SYS_MEMBERSHIPS:READ": "org:sys_memberships:read",
  "ORG:SYS_DOMAINS:MANAGE": "org:sys_domains:manage",
  "ORG:CAMPAIGNS:GLOBAL_READ": "org:campaigns:global_read",
  "ORG:SYS_BILLING:MANAGE": "org:sys_billing:manage",
  "ORG:SYS_PROFILE:MANAGE": "org:sys_profile:manage",
  "ORG:CONTACTS:READ": "org:contacts:read",
  "ORG:SYS_BILLING:READ": "org:sys_billing:read",
} as const;

export const ROLES = {
  "Admin": "org:admin",
  "Member": "org:member",
} as const;

export const ROLE_PERMISSIONS: Record<ClerkRoleKey, ClerkPermissionKey[]> = {
  "org:admin": ["org:campaigns:global_read", "org:sys_domains:manage", "org:sys_domains:read", "org:sys_memberships:manage", "org:sys_memberships:read", "org:sys_profile:delete", "org:sys_profile:manage", "org:sys_billing:manage", "org:sys_billing:read", "org:campaigns:delete", "org:campaigns:global_create", "org:campaigns:global_delete", "org:campaigns:global_update", "org:campaigns:read", "org:campaigns:update", "org:contacts:delete", "org:contacts:global_create", "org:contacts:global_delete", "org:contacts:global_read", "org:contacts:global_update", "org:contacts:read", "org:contacts:update", "org:crm_accounts:delete", "org:crm_accounts:global_create", "org:crm_accounts:global_delete", "org:crm_accounts:global_read", "org:crm_accounts:global_update", "org:crm_accounts:read", "org:crm_accounts:update", "org:opportunities:delete", "org:opportunities:global_create", "org:opportunities:global_delete", "org:opportunities:global_read", "org:opportunities:global_update", "org:opportunities:read", "org:opportunities:update", "org:pipelines:delete", "org:pipelines:global_create", "org:pipelines:global_delete", "org:pipelines:global_read", "org:pipelines:global_update", "org:pipelines:read", "org:pipelines:update"],
  "org:member": ["org:sys_memberships:read", "org:sys_billing:read", "org:campaigns:read", "org:campaigns:update", "org:contacts:global_create", "org:contacts:read", "org:contacts:update", "org:contacts:delete", "org:crm_accounts:delete", "org:crm_accounts:global_create", "org:crm_accounts:read", "org:crm_accounts:update", "org:opportunities:read", "org:opportunities:update", "org:opportunities:global_create", "org:opportunities:delete", "org:pipelines:global_create", "org:pipelines:read", "org:pipelines:update", "org:pipelines:delete"],
};
